version: "0.1"

services:

  postgres1:
    container_name: "postgres-test2"
    image: postgres:16.0
    environment:
      POSTGRES_DB: "db_test2"
      POSTGRES_USER: "denysm"
      POSTGRES_PASSWORD: "AnySecretPassword!!"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
